language: node_js
node_js:
  - '12'
  - '14'
install:
  - npm install -g coveralls
  - npm install
script:
  - export NODE_ICU_DATA=node_modules/full-icu/
  - npm run lint
  - npm run test:cover
  - cat ./coverage/lcov.info | coveralls
