name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          node -v
          npm -v
          npm install -f
          rm -rf browser-test/.gitignore
          npm run browser:compile

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: browser-test # The folder the action should deploy.
